#include "TrailToolsXml.h"

#include <cstdio>
#include <sstream>
#include <string>

#include <windows.h>

namespace
{
	std::string EscAttr(const std::string& s)
	{
		std::string o;
		o.reserve(s.size() + 8);
		for (char c : s)
		{
			switch (c)
			{
			case '&': o += "&amp;"; break;
			case '"': o += "&quot;"; break;
			case '<': o += "&lt;"; break;
			case '>': o += "&gt;"; break;
			default: o.push_back(c); break;
			}
		}
		return o;
	}

	void EmitCategory(std::ostringstream& os, const TrailToolsDetail::CategoryNode& n, int indent)
	{
		std::string pad(static_cast<size_t>(indent), '\t');
		os << pad << "<MarkerCategory name=\"" << EscAttr(n.name)
			<< "\" DisplayName=\"" << EscAttr(n.displayName) << "\"";
		if (!n.iconFile.empty())
			os << " iconFile=\"" << EscAttr(n.iconFile) << "\"";
		if (!n.texture.empty())
			os << " texture=\"" << EscAttr(n.texture) << "\"";
		if (n.fadeNear >= 0.f)
			os << " fadeNear=\"" << n.fadeNear << "\"";
		if (n.fadeFar >= 0.f)
			os << " fadeFar=\"" << n.fadeFar << "\"";
		if (n.children.empty())
		{
			os << "/>\n";
			return;
		}
		os << ">\n";
		for (const auto& ch : n.children)
			EmitCategory(os, ch, indent + 1);
		os << pad << "</MarkerCategory>\n";
	}
}

std::string TrailToolsXml::EmitOverlayData(const TrailToolsDetail::DraftPack& pack)
{
	std::ostringstream os;
	os << "<!-- Generated by GW2-InGame-Helper Trail Tools -->\n";
	os << "<OverlayData>\n";
	EmitCategory(os, pack.root, 1);
	os << "\t<POIs>\n";
	for (const auto& p : pack.pois)
	{
		char line[512]{};
		std::snprintf(line, sizeof(line),
			"\t\t<POI MapID=\"%u\" xpos=\"%.6g\" ypos=\"%.6g\" zpos=\"%.6g\" type=\"%s\" GUID=\"%s\"/>\n",
			p.mapId, p.x, p.y, p.z, EscAttr(p.type).c_str(), EscAttr(p.guid).c_str());
		os << line;
	}
	for (const auto& t : pack.trails)
	{
		if (t.fileRel.empty() || t.type.empty())
			continue;
		os << "\t\t<Trail type=\"" << EscAttr(t.type)
			<< "\" trailData=\"" << EscAttr(t.fileRel) << "\"/>\n";
	}
	/* Include active trail if it has points and is not already listed. */
	if (pack.active.points.size() >= 2 && !pack.active.fileRel.empty() && !pack.active.type.empty())
	{
		bool listed = false;
		for (const auto& t : pack.trails)
		{
			if (t.fileRel == pack.active.fileRel)
			{
				listed = true;
				break;
			}
		}
		if (!listed)
		{
			os << "\t\t<Trail type=\"" << EscAttr(pack.active.type)
				<< "\" trailData=\"" << EscAttr(pack.active.fileRel) << "\"/>\n";
		}
	}
	os << "\t</POIs>\n";
	os << "</OverlayData>\n";
	return os.str();
}

bool TrailToolsXml::WriteOverlayFile(const std::wstring& path, const TrailToolsDetail::DraftPack& pack)
{
	const std::string xml = EmitOverlayData(pack);
	HANDLE h = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS,
		FILE_ATTRIBUTE_NORMAL, nullptr);
	if (h == INVALID_HANDLE_VALUE)
		return false;
	DWORD written = 0;
	const BOOL ok = WriteFile(h, xml.data(), static_cast<DWORD>(xml.size()), &written, nullptr);
	CloseHandle(h);
	return ok && written == xml.size();
}
