#!/usr/bin/env python3
"""Generate src/Sites.gen.cpp from data/sites.json (canonical catalog)."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JSON = ROOT / "data" / "sites.json"
DEFAULT_OUT = ROOT / "src" / "Sites.gen.cpp"


def cpp_string(s: str | None) -> str:
	if s is None:
		return "nullptr"
	# Escape for C++ string literal
	out = ['"']
	for ch in s:
		o = ord(ch)
		if ch == "\\":
			out.append("\\\\")
		elif ch == '"':
			out.append('\\"')
		elif ch == "\n":
			out.append("\\n")
		elif ch == "\r":
			out.append("\\r")
		elif ch == "\t":
			out.append("\\t")
		elif o < 0x20:
			out.append(f"\\x{o:02x}")
		else:
			out.append(ch)
	out.append('"')
	return "".join(out)


def validate(payload: dict) -> list[dict]:
	errors: list[str] = []
	if payload.get("version") != 1:
		errors.append(f"unsupported version: {payload.get('version')!r}")
	sites = payload.get("sites")
	if not isinstance(sites, list) or not sites:
		errors.append("sites must be a non-empty array")
		sites = []
	count = payload.get("count")
	if isinstance(count, int) and count != len(sites):
		errors.append(f"count {count} != len(sites) {len(sites)}")

	seen: set[str] = set()
	cats: list[str] = []
	last: str | None = None
	for i, s in enumerate(sites):
		if not isinstance(s, dict):
			errors.append(f"sites[{i}] not an object")
			continue
		sid = s.get("id") or ""
		cat = s.get("category") or ""
		for field in ("id", "category", "label", "title", "homeUrl"):
			if not s.get(field):
				errors.append(f"sites[{i}] empty {field}")
		if sid in seen:
			errors.append(f"duplicate id: {sid!r}")
		seen.add(sid)
		if last is None or cat != last:
			if cat in cats:
				errors.append(f"category {cat!r} reappears (not contiguous) at id={sid}")
			else:
				cats.append(cat)
			last = cat
		for key in s:
			if key not in (
				"id",
				"category",
				"label",
				"title",
				"homeUrl",
				"searchUrlPrefix",
				"searchUrlSuffix",
			):
				errors.append(f"sites[{i}] unknown key {key!r}")

	if errors:
		for e in errors:
			print(f"error: {e}", file=sys.stderr)
		raise SystemExit(1)
	return sites  # type: ignore[return-value]


def generate(sites: list[dict]) -> str:
	lines = [
		"/* AUTO-GENERATED by tools/gen_sites_cpp.py — DO NOT EDIT.",
		"   Canonical catalog: data/sites.json",
		"   Regenerate: make gen-sites */",
		"",
		'#include "Sites.h"',
		"",
		"SiteDef gSites[] = {",
	]
	for s in sites:
		prefix = s.get("searchUrlPrefix")
		suffix = s.get("searchUrlSuffix")
		lines.append("\t{")
		lines.append(f"\t\t{cpp_string(s['id'])},")
		lines.append(f"\t\t{cpp_string(s['category'])},")
		lines.append(f"\t\t{cpp_string(s['label'])},")
		lines.append(f"\t\t{cpp_string(s['title'])},")
		lines.append(f"\t\t{cpp_string(s['homeUrl'])},")
		lines.append(f"\t\t{cpp_string(prefix) if prefix is not None else 'nullptr'},")
		lines.append(f"\t\t{cpp_string(suffix) if suffix is not None else 'nullptr'},")
		lines.append("\t},")
	lines.append("};")
	lines.append("")
	lines.append(f"extern const int kSiteCount = {len(sites)};")
	lines.append("")
	return "\n".join(lines)


def main() -> int:
	ap = argparse.ArgumentParser(description=__doc__)
	ap.add_argument("json", nargs="?", type=Path, default=DEFAULT_JSON)
	ap.add_argument("out", nargs="?", type=Path, default=DEFAULT_OUT)
	ap.add_argument(
		"--check",
		action="store_true",
		help="Fail if committed output differs from regenerated content",
	)
	args = ap.parse_args()

	payload = json.loads(args.json.read_text(encoding="utf-8"))
	sites = validate(payload)
	text = generate(sites)

	if args.check:
		if not args.out.is_file():
			print(f"error: missing {args.out}", file=sys.stderr)
			return 1
		existing = args.out.read_text(encoding="utf-8")
		if existing != text:
			print(f"error: {args.out} is stale — run: make gen-sites", file=sys.stderr)
			return 1
		print(f"ok: {args.out} matches {args.json} ({len(sites)} sites)")
		return 0

	args.out.parent.mkdir(parents=True, exist_ok=True)
	args.out.write_text(text, encoding="utf-8")
	print(f"wrote {len(sites)} sites → {args.out}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
